var e=this;function g(a,b,d){return a.call.apply(a.bind,arguments)}function h(a,b,d){if(!a)throw Error();if(2<arguments.length){var c=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,c);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}}function k(a,b,d){k=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?g:h;return k.apply(null,arguments)}
function l(a,b){var d=a.split("."),c=e;d[0]in c||!c.execScript||c.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)d.length||void 0===b?c[f]?c=c[f]:c=c[f]={}:c[f]=b};function m(a){var b=document.createElement("script");b.src=a;b.type="text/javascript";b.async=!0;document.getElementsByTagName("head")[0].appendChild(b)}l("load_javascript",m);function n(a,b,d){var c=new Date;c.setTime((new Date).getTime()+36E5*d);document.cookie=a+"="+encodeURIComponent(b)+";expires="+c.toGMTString()}l("setcookie",n);
l("getcookie",function(a){if(0<document.cookie.length){var b=document.cookie.indexOf(a+"=");if(-1!=b)return b=b+a.length+1,a=document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),decodeURIComponent(document.cookie.substring(b,a))}return""});
function p(a,b,d){var c=new XMLHttpRequest;try{c.open("POST",a,!0),c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.onreadystatechange=function(){4==c.readyState&&200==c.status&&c.responseText&&d&&d(c.responseText)},c.send(b)}catch(f){}}function q(a){r(window,"load",a)}l("addOnLoad",q);
l("openPopUp",function(a){1E3<screen.width?(width=800,height=600):(width=600,height=450);screenX=.5*(screen.width-width);screenY=.5*(screen.height-height);winargs="width="+width+",height="+height+",screenX="+screenX+",screenY="+screenY+",location=no,scrollbars=yes,toolbar=no,menubar=no,status=no,titlebar=no";(win1=window.open(a,"_blank",winargs))&&win1.focus()});l("generateId",function(){for(var a="",b=0;8>b;b++)a+=Math.round(65536*(1+Math.random())).toString(16).substring(1);return a});
function r(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,function(){return d.call(a,window.event)})};var t=0;function u(a){for(i=1;i<=a;i++)document.getElementById("star"+i).setAttribute("src","/images/orangestar.png");for(i=a+1;5>=i;i++)document.getElementById("star"+i).setAttribute("src","/images/graystar.png")}function v(){u(t)}
function w(a){t=a;u(a);p("page_ratings.php","rating="+a+"&url="+escape(document.location.href)+"&screenWidth="+screen.width+"&screenHeight="+screen.height+"&colorDepth="+screen.colorDepth+"&cookiesEnabled="+navigator.cookieEnabled);confirm(tr_comment)&&(document.location.href="contact.php?tag=ranking")};l("activate",function(){n("activate","1",1)});l("trimCheckInput",function(a){a.value=a.value.replace(/^\s*([\S\s]*?)\s*$/,"$1");var b=/^[A-Za-z0-9_.-]+$/;if(/^(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(?:\\.(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])){3}|(?:(?:[0-9a-fA-F:]){1,4}(?:(?::(?:[0-9a-fA-F]){1,4}|:)){2,7})+$/.test(a.value)||b.test(a.value))return!0;alert(tr_enter_valid_ip_or_domain);return!1});
l("resizeMe",function(a){a.style.height="3em";a.style.height=a.scrollHeight+10+"px"});document.getElementById("ipv4")&&(p("https://ipv4.infobyip.com/ipdetector.php","",function(a){document.getElementById("ipv4").innerHTML=a}),p("https://ipv6.infobyip.com/ipdetector.php","test",function(a){document.getElementById("ipv6").innerHTML=a}));var x=x||[];l("_gaq",x);x.push(["_setAccount","UA-404570-9"]);x.push(["_setDomainName","infobyip.com"]);x.push(["_trackPageview"]);
q(function(){m("https://www.google-analytics.com/ga.js");m("https://s7.addthis.com/js/300/addthis_widget.js#pubid=linkedweb&domready=1");for(var a=document.getElementsByTagName("textarea"),b=0;b<a.length;b++){var d=a[b];if(d.onkeydown)d.onkeydown()}});var y=["bingsandbox.com"],z;if(!(z=top==self))a:{var A,B=document.location.href.substring(7).split("/")[0],B=B.replace(/local$/,"com");A=B=B.replace(/^.*?[.]/,"");for(var C=0;C<y.length;C++)if(y[C]===A){z=!0;break a}z=!1}z||top.location.replace(location);
for(var D=1;5>=D;D++){var E=document.getElementById("star"+D);E&&(r(E,"mouseover",k(u,null,D)),r(E,"click",k(w,null,D)),r(E,"mouseout",v))};
