var f=this;function k(a,b,c){return a.call.apply(a.bind,arguments)}function l(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function m(a,b,c){m=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?k:l;return m.apply(null,arguments)}
function n(a,b){var c=a.split("."),d=f;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var g;c.length&&(g=c.shift());)c.length||void 0===b?d[g]?d=d[g]:d=d[g]={}:d[g]=b};function p(a){var b=document.createElement("script");b.src=a;b.type="text/javascript";b.async=!0;document.getElementsByTagName("head")[0].appendChild(b)}n("load_javascript",p);function q(a,b,c){var d=new Date;d.setTime((new Date).getTime()+36E5*c);document.cookie=a+"="+encodeURIComponent(b)+";expires="+d.toGMTString()}n("setcookie",q);
n("getcookie",function(a){if(0<document.cookie.length){var b=document.cookie.indexOf(a+"=");if(-1!=b)return b=b+a.length+1,a=document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),decodeURIComponent(document.cookie.substring(b,a))}return""});
function r(a,b,c){var d=new XMLHttpRequest;try{d.open("POST",a,!0),d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),d.onreadystatechange=function(){4==d.readyState&&200==d.status&&d.responseText&&c&&c(d.responseText)},d.send(b)}catch(g){}}function t(a){u(window,"load",a)}n("addOnLoad",t);
n("openPopUp",function(a){1E3<screen.width?(width=800,height=600):(width=600,height=450);screenX=.5*(screen.width-width);screenY=.5*(screen.height-height);winargs="width="+width+",height="+height+",screenX="+screenX+",screenY="+screenY+",location=no,scrollbars=yes,toolbar=no,menubar=no,status=no,titlebar=no";(win1=window.open(a,"_blank",winargs))&&win1.focus()});n("generateId",function(){for(var a="",b=0;8>b;b++)a+=Math.round(65536*(1+Math.random())).toString(16).substring(1);return a});
function u(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,function(){return c.call(a,window.event)})};var v=0;function w(a){for(i=1;i<=a;i++)document.getElementById("star"+i).setAttribute("src","/images/orangestar.png");for(i=a+1;5>=i;i++)document.getElementById("star"+i).setAttribute("src","/images/graystar.png")}function x(){w(v)}
function y(a){v=a;w(a);r("page_ratings.php","rating="+a+"&url="+escape(document.location.href)+"&screenWidth="+screen.width+"&screenHeight="+screen.height+"&colorDepth="+screen.colorDepth+"&cookiesEnabled="+navigator.cookieEnabled);confirm(tr_comment)&&(document.location.href="contact.php?tag=ranking")};n("activate",function(){q("activate","1",1)});n("trimCheckInput",function(a){a.value=a.value.replace(/^\s*([\S\s]*?)\s*$/,"$1");var b=/^[A-Za-z0-9_.-]+$/;if(/^(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(?:\\.(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])){3}|(?:(?:[0-9a-fA-F:]){1,4}(?:(?::(?:[0-9a-fA-F]){1,4}|:)){2,7})+$/.test(a.value)||b.test(a.value))return!0;alert(tr_enter_valid_ip_or_domain);return!1});
n("resizeMe",function(a){a.style.height="3em";a.style.height=a.scrollHeight+10+"px"});document.getElementById("ipv4")&&(r("https://ipv4.infobyip.com/ipdetector.php","",function(a){document.getElementById("ipv4").innerHTML=a}),r("https://ipv6.infobyip.com/ipdetector.php","test",function(a){document.getElementById("ipv6").innerHTML=a}));var z=z||[];n("_gaq",z);z.push(["_setAccount","UA-404570-9"]);z.push(["_setDomainName","infobyip.com"]);z.push(["_trackPageview"]);
t(function(){p("");p("");for(var a=document.getElementsByTagName("textarea"),b=0;b<a.length;b++){var c=a[b];if(c.onkeydown)c.onkeydown()}});var A=["bingsandbox.com"],B;if(!(B=top==self))a:{var C,D=document.location.href.substring(7).split("/")[0],D=D.replace(/local$/,"com");C=D=D.replace(/^.*?[.]/,"");for(var E=0;E<A.length;E++)if(A[E]===C){B=!0;break a}B=!1}B||top.location.replace(location);
for(var F=1;5>=F;F++){var G=document.getElementById("star"+F);G&&(u(G,"mouseover",m(w,null,F)),u(G,"click",m(y,null,F)),u(G,"mouseout",x))};function H(a){return a[Math.floor(Math.random()*a.length)]}
function I(){var a="abcdefgihjklmnopqrstuvwxyz",b="ABCDEFGIHJKLMNOPQRSTUVWXYZ",c="0123456789",d=document.getElementById("special_chars").value,g=document.getElementById("pass_len").value;document.getElementById("excl_sim").checked&&(c=c.replace("0",""),a=a.replace("i","").replace("l","").replace("o",""),b=b.replace("I","").replace("L","").replace("O",""));var h="",e="";document.getElementById("incl_low").checked&&(e+=H(a),h+=a);document.getElementById("incl_cap").checked&&(e+=H(b),h+=b);document.getElementById("incl_dig").checked&&
(e+=H(c),h+=c);document.getElementById("incl_spe").checked&&(e+=H(d),h+=d);for(;e.length<g;)e+=H(h);a=e;for(b="";a.length;)c=Math.floor(Math.random()*a.length),b+=a[c],a=a.substring(0,c)+a.substring(c+1);return b}
n("generatePassword",function(){document.getElementById("pass_row").style.display="";try{for(var a=Math.min(99,parseInt(document.getElementById("pass_count").value)),b=[],c=0;c<a;c++)b.push(I());var d=document.getElementById("password");d.setAttribute("rows",a);d.value=b.join("\n");d.style.height=3+a+"em";d.focus();d.select()}catch(g){console.log(g)}return!1});
